use crate::utils::define_appendix;

define_appendix! {
    InfringementType {
        0 => BlockingBySlowDriving => "Blocking by slow driving",
        1 => BlockingByWrongWayDriving => "Blocking by wrong way driving",
        2 => ReversingOffStartLine => "Reversing off the start line",
        3 => BigCollision => "Big Collision",
        4 => SmallCollision => "Small Collision",
        5 => CollisionFailedHandBackSingle => "Collision failed to hand back position single",
        6 => CollisionFailedHandBackMultiple => "Collision failed to hand back position multiple",
        7 => CornerCuttingGainedTime => "Corner cutting gained time",
        8 => CornerCuttingOvertakeSingle => "Corner cutting overtake single",
        9 => CornerCuttingOvertakeMultiple => "Corner cutting overtake multiple",
        10 => CrossedPitExitLane => "Crossed pit exit lane",
        11 => IgnoringBlueFlags => "Ignoring blue flags",
        12 => IgnoringYellowFlags => "Ignoring yellow flags",
        13 => IgnoringDriveThrough => "Ignoring drive through",
        14 => TooManyDriveThroughs => "Too many drive throughs",
        15 => DriveThroughReminderServeWithinNLaps => "Drive through reminder serve within n laps",
        16 => DriveThroughReminderServeThisLap => "Drive through reminder serve this lap",
        17 => PitLaneSpeeding => "Pit lane speeding",
        18 => ParkedForTooLong => "Parked for too long",
        19 => IgnoringTyreRegulations => "Ignoring tyre regulations",
        20 => TooManyPenalties => "Too many penalties",
        21 => MultipleWarnings => "Multiple warnings",
        22 => ApproachingDisqualification => "Approaching disqualification",
        23 => TyreRegulationsSelectSingle => "Tyre regulations select single",
        24 => TyreRegulationsSelectMultiple => "Tyre regulations select multiple",
        25 => LapInvalidatedCornerCutting => "Lap invalidated corner cutting",
        26 => LapInvalidatedRunningWide => "Lap invalidated running wide",
        27 => CornerCuttingRanWideGainedTimeMinor => "Corner cutting ran wide gained time minor",
        28 => CornerCuttingRanWideGainedTimeSignificant => "Corner cutting ran wide gained time significant",
        29 => CornerCuttingRanWideGainedTimeExtreme => "Corner cutting ran wide gained time extreme",
        30 => LapInvalidatedWallRiding => "Lap invalidated wall riding",
        31 => LapInvalidatedFlashbackUsed => "Lap invalidated flashback used",
        32 => LapInvalidatedResetToTrack => "Lap invalidated reset to track",
        33 => BlockingPitlane => "Blocking the pitlane",
        34 => JumpStart => "Jump start",
        35 => SafetyCarToCarCollision => "Safety car to car collision",
        36 => SafetyCarIllegalOvertake => "Safety car illegal overtake",
        37 => SafetyCarExceedingAllowedPace => "Safety car exceeding allowed pace",
        38 => VirtualSafetyCarExceedingAllowedPace => "Virtual safety car exceeding allowed pace",
        39 => FormationLapBelowAllowedSpeed => "Formation lap below allowed speed",
        40 => FormationLapParking => "Formation lap parking",
        41 => RetiredMechanicalFailure => "Retired mechanical failure",
        42 => RetiredTerminallyDamaged => "Retired terminally damaged",
        43 => SafetyCarFallingTooFarBack => "Safety car falling too far back",
        44 => BlackFlagTimer => "Black flag timer",
        45 => UnservedStopGoPenalty => "Unserved stop go penalty",
        46 => UnservedDriveThroughPenalty => "Unserved drive through penalty",
        47 => EngineComponentChange => "Engine component change",
        48 => GearboxChange => "Gearbox change",
        49 => ParcFerméChange => "Parc Fermé change",
        50 => LeagueGridPenalty => "League grid penalty",
        51 => RetryPenalty => "Retry penalty",
        52 => IllegalTimeGain => "Illegal time gain",
        53 => MandatoryPitstop => "Mandatory pitstop",
        54 => AttributeAssigned => "Attribute assigned"
    }
}
