use crate::utils::define_appendix;

define_appendix!(TrackId {
    0 => Melbourne,
    2 => Shanghai,
    3 => Sakhir => "Sakhir (Bahrain)",
    4 => Catalunya,
    5 => Monaco,
    6 => Montreal,
    7 => Silverstone,
    9 => Hungaroring,
    10 => Spa,
    11 => Monza,
    12 => Singapore,
    13 => Suzuka,
    14 => AbuDhabi => "Abu Dhabi",
    15 => Texas,
    16 => Brazil,
    17 => Austria,
    19 => Mexico,
    20 => Baku => "Baku (Azerbaijan)",
    26 => Zandvoort,
    27 => Imola,
    29 => Jeddah,
    30 => Miami,
    31 => LasVegas => "Las Vegas",
    32 => Losail,
    39 => SilverstoneReverse => "Silverstone (Reverse)",
    40 => AustriaReverse => "Austria (Reverse)",
    41 => ZandvoortReverse => "Zandvoort (Reverse)"
});
